# Generated by Django 3.2.6 on 2021-08-27 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movies.utils.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('movie_type', models.CharField(blank=True, max_length=50, verbose_name='Movie type')),
                ('rating', models.CharField(blank=True, max_length=30, verbose_name='Rating')),
                ('movie_language', models.CharField(blank=True, max_length=50, verbose_name='Language')),
                ('production_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1200)], verbose_name='Production Year')),
                ('director', models.CharField(blank=True, max_length=60, verbose_name='Director')),
                ('actors', models.CharField(blank=True, max_length=400, verbose_name='Actors')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=movies.utils.functions.file_name_setter, verbose_name='Cover')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'Movie',
                'unique_together': {('name', 'genre', 'movie_type')},
            },
        ),
    ]
